# Generated by Django 4.1.3 on 2022-11-11 15:13

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceplan',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200000)),
                ('plan_type', models.CharField(max_length=500)),
                ('cost', models.IntegerField()),
                ('meas_type', models.CharField(max_length=500)),
                ('is_active', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=500, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=500)),
                ('last_name', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(max_length=500, unique=True)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500, unique=True)),
                ('is_staff', models.IntegerField(blank=True)),
                ('is_active', models.IntegerField(blank=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.IntegerField(blank=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('address1', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=500)),
                ('zip', models.CharField(blank=True, max_length=500)),
                ('state', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=500)),
                ('credit_card_number', models.CharField(blank=True, max_length=500)),
                ('name_of_card', models.CharField(blank=True, max_length=500)),
                ('expire_month', models.CharField(blank=True, max_length=500)),
                ('expire_year', models.CharField(blank=True, max_length=500)),
                ('billing_address', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('planId', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
