"""
Django settings for pluvialApi project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from pathlib import Path
import os
from datetime import datetime, timedelta
from datetime import datetime, timedelta

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y3wnj060+ysqu0j6@_@@abru@sipql&_xi^#n6^sjh(c^ic+&+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'rest_framework_simplejwt'

]


# Configure the authentication classes
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # other authentication classes
    ],
}

# Configure the JWT token settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # other settings
}



# Configure the authentication classes
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # other authentication classes
    ],
}

# Configure the JWT token settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # other settings
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pluvialApi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pluvialApi.wsgi.application'

#mongodb+srv://pactime:0EM1eJ2N8uXWCEts@cluster0.i5xrelh.mongodb.net/owleeloc?retryWrites=true&w=majority
DATABASES = {
        'default': {
            'ENGINE': 'djongo',
            'NAME': 'pluvial',
            'ENFORCE_SCHEMA': False,
            'CLIENT': {
                'host':"mongodb+srv://pactime:0EM1eJ2N8uXWCEts@cluster0.i5xrelh.mongodb.net/pluvial?retryWrites=true&w=majority"
            }
        }
}
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATICFILES_DIRS = (str(BASE_DIR.joinpath('static')),)
STATIC_URL = '/static/'


# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PLANET_API_KEY = 'PLAK4ce06855d756460bb7afdf66c88d2049'
WEATHER_SUNSCRIPTION_KEY = '0tbRYbnJn25-al_7xML3Z2IWi-JnCLfZUx8qM2ZVGZo'
WEATHER_API = 'https://atlas.microsoft.com/weather/currentConditions/json?api-version=1.0'
BLOB_STORAGE = {  
         "account": "pluvialblobstorage",
         "container": "planet",
         "sas_token": "TBb5TIBOyepf/dIDPMWxQQS+XeYQmBsqMq3jQ5MCnJAarKVF00J3+Axn/sZwF8Srb7zFcH9hoI7D+AStQZu4rg==",
         "storage_endpoint_suffix": "core.windows.net",
         "path_prefix": "planet/"
      }
BLOB_STORAGE_STRING = "DefaultEndpointsProtocol=https;AccountName=pluvialblobstorage;AccountKey=TBb5TIBOyepf/dIDPMWxQQS+XeYQmBsqMq3jQ5MCnJAarKVF00J3+Axn/sZwF8Srb7zFcH9hoI7D+AStQZu4rg==;EndpointSuffix=core.windows.net"
BLOB_STORAGE_CONTAINER = "planet"

JWT_SECRET = "hiitytyrty677676vhvr5dr"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "ganeshgaride53@gmail.com"
EMAIL_HOST_PASSWORD = "pzcnarzdtednjfpj"
FE_URL = "http://localhost:8000/"